/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'attendee-categories': AttendeeCategory;
    groups: Group;
    locations: Location;
    users: User;
    'weekly-schedule': WeeklySchedule;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendee-categories".
 */
export interface AttendeeCategory {
  id: number;
  name: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  name: string;
  description?: string | null;
  id: string;
  slug: string;
  attendeeCategories: (number | AttendeeCategory)[];
  location: number | Location;
  schedule?:
    | {
        weekdays: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[];
        startTime: string;
        endTime: string;
        additionalInfo?: string | null;
        location?: (number | null) | Location;
        id?: string | null;
      }[]
    | null;
  'booking-required'?: boolean | null;
  contactDetails?:
    | {
        type: 'url' | 'email' | 'phone';
        value: string;
        customLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  moderators?: (number | User)[] | null;
  status: 'pending' | 'active' | 'inactive' | 'archived';
  price?:
    | {
        'price-label': string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  postcode: string;
  address: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'user' | 'moderator' | 'admin';
  groupsFollowed?: (string | Group)[] | null;
  groupsManaged?: (string | Group)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-schedule".
 */
export interface WeeklySchedule {
  id: number;
  weekday: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
  startTime: string;
  endTime: string;
  additionalInfo?: string | null;
  location?: (number | null) | Location;
  status?: ('active' | 'cancelled' | 'postponed' | 'hiatus' | 'tbc') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}